# Generated by Django 4.2.4 on 2023-09-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='OrderDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordermodel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopapp.ordermodel')),
                ('producmodel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopapp.productmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(through='myshopapp.OrderDetailsModel', to='myshopapp.productmodel'),
        ),
    ]
