# Generated by Django 4.2.4 on 2023-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopapp', '0002_alter_productmodel_image_orderdetailsmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailsmodel',
            name='quantity_in_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(through='myshopapp.OrderDetailsModel', to='myshopapp.productmodel'),
        ),
    ]
